# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1a5a6d2338836c37405d2e21b8e098d"
name = "BulkGenie AI"
handle = "bulkgenie-ai"
application_url = "https://bulkgenie.fly.dev"
embedded = true

# [app_preferences]
# url = "https://bulkgenie.fly.dev/app/settings"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://bulkgenie.fly.dev/auth/callback",
  "https://bulkgenie.fly.dev/auth/shopify/callback",
  "https://bulkgenie.fly.dev/api/auth/callback"
]
